# -*- coding: utf-8 -*-
"""Assignment5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1myAyUszhFnGRsCGIsD8XwAMXeKtdbe5o
"""

import streamlit as st

# Title of the app
st.title("Greeting App")

# Create a text input box
user_name = st.text_input("Enter your name:")

# Greet the user when they enter their name
if user_name:
    st.write(f"Hello, {user_name}!")